version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./db_data/db:/var/lib/mysql"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mariadb
    networks:
      - backend

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/rails:6-debian-10
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/app

networks:
  backend:
    driver: bridge